server {
    listen 80;
    listen [::]:80;
    server_name personaverse.space www.personaverse.space;
    root /var/www/html;
    index index.html;
    
    location / {
        try_files $uri $uri/ =404;
    }
    
    location /_next/ {
        alias /var/www/html/_next/;
    }
}

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    return 301 http://personaverse.space$request_uri;
}
