server {
    listen 80 default_server;
    listen [::]:80 default_server;
    
    server_name 107.170.57.250 _;
    
    root /var/www/personaverse;
    index index.html;
    
    location / {
        try_files $uri $uri/ /index.html;
    }
    
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml;
}
